//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspector()
        {
<<<<<<< HEAD:FAP/Inspector.cs
            this.Planning = new HashSet<Planning>();
=======
            this.Plannings = new HashSet<Planning>();
>>>>>>> Martijn:FAP/FAP/Inspector.cs
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<int> telephone_nr { get; set; }
        public string postcode { get; set; }
        public string house_number { get; set; }
    
        public virtual ID ID1 { get; set; }
<<<<<<< HEAD:FAP/Inspector.cs
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planning> Planning { get; set; }
=======
        public virtual Inspector_shedule Inspector_shedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planning> Plannings { get; set; }
>>>>>>> Martijn:FAP/FAP/Inspector.cs
    }
}
