
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FAP.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class Answer1
{

    public int Id { get; set; }

    public int questionId { get; set; }

    public string Subject { get; set; }

    public string answer1 { get; set; }

    public byte[] Image { get; set; }



    public virtual Question Question { get; set; }

}

}
