
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FAP.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Employee()
    {

        this.Invoices = new HashSet<Invoice>();

        this.Plannings = new HashSet<Planning>();

        this.Quotations = new HashSet<Quotation>();

    }


    public int id { get; set; }

    public int department_id { get; set; }

    public string name { get; set; }

    public string surname { get; set; }

    public Nullable<int> acces_level { get; set; }

    public string position { get; set; }

    public string postcode { get; set; }

    public string house_number { get; set; }

    public System.DateTime date_of_birth { get; set; }



    public virtual Bank_Account Bank_Account { get; set; }

    public virtual Department Department { get; set; }

    public virtual Inlogdata Inlogdata { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoice> Invoices { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Planning> Plannings { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Quotation> Quotations { get; set; }

}

}
