//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FAPEntities : DbContext
    {
        public FAPEntities()
            : base("name=FAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<Bank_Account> Bank_Account { get; set; }
        public virtual DbSet<ComboQuestion> ComboQuestion { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<ID> ID { get; set; }
        public virtual DbSet<Inlogdata> Inlogdata { get; set; }
        public virtual DbSet<Inspector> Inspector { get; set; }
        public virtual DbSet<Inspector_Bank_Account> Inspector_Bank_Account { get; set; }
        public virtual DbSet<Inspector_shedule> Inspector_shedule { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<MultipleChoice> MultipleChoice { get; set; }
        public virtual DbSet<MultiplechoiceAnswers> MultiplechoiceAnswers { get; set; }
        public virtual DbSet<OpenSubjectQuestion> OpenSubjectQuestion { get; set; }
        public virtual DbSet<Payment_status> Payment_status { get; set; }
        public virtual DbSet<Planning> Planning { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Questionnaire> Questionnaire { get; set; }
        public virtual DbSet<Quotation> Quotation { get; set; }
        public virtual DbSet<StandardQuestion> StandardQuestion { get; set; }
        public virtual DbSet<StandardQuestionsList> StandardQuestionsList { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
