//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiplechoiceAnswers
    {
        public int Id { get; set; }
        public int question_id { get; set; }
        public string Answer { get; set; }
    
        public virtual MultipleChoice MultipleChoice { get; set; }
    }
}
