//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medewerker
    {
        public int id { get; set; }
        public Nullable<int> department_id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<int> acces_level { get; set; }
        public string position { get; set; }
        public string postcode { get; set; }
        public string house_number { get; set; }
    }
}
