//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FAPDbEntities : DbContext
    {
        public FAPDbEntities()
            : base("name=FAPDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Bank_Account> Bank_Account { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<ID> IDs { get; set; }
        public virtual DbSet<Inlogdata> Inlogdatas { get; set; }
        public virtual DbSet<Inspector> Inspectors { get; set; }
        public virtual DbSet<Inspector_shedule> Inspector_shedule { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Payment_status> Payment_status { get; set; }
        public virtual DbSet<Planning> Plannings { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Questionnaire> Questionnaires { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<StandardQuestion> StandardQuestions { get; set; }
        public virtual DbSet<StandardQuestionsList> StandardQuestionsLists { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
